### ISSUE TITLE
这个扩张做的非常好！一点小建议～

### ISSUE THREAD

**Issue by dodolook8** [tnychn/opencc-extension#1]
默认的输入框太小了，能否每次拉伸其大小后保存住大小？

有时候复制的文字较多，这个默认的框太小，每次都要拖开很麻烦。最起码默认的大小应该是现在的3-4倍大更好。谢谢～

感谢你的辛苦，望opencc以后更新后，每隔一年左右升级下库，不用太占有你时间。

**Comment by tnychn** [comment]
✅ 已在 [`v0.3.1`](https://github.com/tnychn/opencc-extension/releases/tag/v0.3.1) 中添加輸入框大小保存及重置功能。
