### ISSUE TITLE
Chrome 擴展功能什麼時候要發佈呢？

### ISSUE THREAD

**Issue by BSBMteam** [tnychn/opencc-extension#11]
Just curious to see if this project is still active! ヾ(≧▽≦*)o

**Comment by tnychn** [comment]
Just migrated the extension to MV3 compatible at [v0.4.0](https://github.com/tnychn/opencc-extension/releases/tag/v0.4.0).
It's now submitted to Chrome Web Store for review. Will close this issue once it's passed and published. :)

**Comment by tnychn** [comment]
Chrome v0.4.0 已發佈 https://chromewebstore.google.com/detail/opencc/jmlbcbhpnfpffhniogblmmiklgbopoif
