### ISSUE TITLE
很多页面遇到 PAGE PROTECTED BY BROWSER

### ISSUE THREAD

**Issue by H4M5TER** [tnychn/opencc-extension#12]
已经给了本扩展全页面权限了，怀疑是其他扩展导致的权限问题，我在 GitHub 就可以正常转。

**Comment by tnychn** [comment]
請問是 Chrome 還是 Firefox？是哪個網站的頁面出現問題？

**Comment by H4M5TER** [comment]
是 Chromium，准确来说是 Vivaldi，但是我现在已无法复现这个问题，先关了
我一开始是在 Steam 商店遇到的，但是之后试其他网页有的也有
