### ISSUE TITLE
There are some errors occur when load

### ISSUE THREAD

**Issue by KoukeFoxes** [tnychn/opencc-extension#14]
`Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.`

`Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.`

<img width="879" alt="image" src="https://user-images.githubusercontent.com/65907692/178749226-56ea2e75-167b-4ffe-a4b6-cc647b3d9951.png">

Microsoft Edge
Version 103.0.1264.51 (Official build) (arm64)

**Comment by tnychn** [comment]
> Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

This is just a warning to developers about migrating to manifest v3. Users can simply ignore it.

> Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.

This is caused by old tabs already open before the extension is installed. To resolve this issue, simply reload all the old tabs so that the extension can be run on those tabs.
